server:
  port: 8081
spring:
  application:
    name: service-edu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/onlinedu?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 192.168.200.132
    port: 6379
    password: abc123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  type-aliases-package: com.hjx.onlineedu.pojo # 别名扫描包
logging:
  level:
    com.hmdp: debug
endpoint: oss-cn-beijing.aliyuncs.com
accessKeyId: LTAI5t6cyNodvBth3BzzmEDG
accessKeySecret: JfAnNKnUFPGuYBtjZPQHipnFJyIxoF
bucketName: hjxuse